name: Firmware Testing

runs:
  using: composite

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install PlatformIO
      shell: bash
      run: pip install platformio

    - name: Run Native Tests
      shell: bash
      working-directory: firmware/esp32
      run: pio test -e native_test
      