name: Firmware Building

runs:
  using: composite

  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"

    - name: Install PlatformIO
      shell: bash
      run: pip install platformio

    - name: Build ESP32 Firmware
      shell: bash
      working-directory: firmware/esp32
      run: pio run -e esp32dev
      