#!/usr/bin/env sh
set -e

echo "Running pre-push tests..."

# 1. Backend Tests (NestJS)
echo "Checking Backend (NestJS)..."

cd backend/nestjs
npm run test -- --watchAll=false
cd ../..

# 2. Frontend Tests
echo "Checking Frontend (Next.js)..."

cd frontend/dashboard
npm run test
cd ../..

# 3. Firmware Tests (PlatformIO)
echo "Placeholder Firmware tests"
cd firmware/esp32
pio test -e native_test
cd ../..


echo "All tests passed. Proceeding with push."